name: Extract plutobook binaries

on: [push, pull_request]

jobs:
  extract:
    runs-on: ubuntu-latest
    permissions:
      packages: read
    container:
      image: ghcr.io/plutoprint/plutobook-manylinux_2_28_x86_64:latest
      
    steps:
      - name: Bundle library, tools, and dependencies
        run: |
          dnf -y install patchelf pax-utils binutils

          mkdir -p /bundle/plutobook/lib /bundle/plutobook/include /bundle/plutobook/tools
          cp -a /usr/lib64/libplutobook.so* /bundle/plutobook/lib/
          cp -r /usr/include/plutobook* /bundle/plutobook/include/
          cp /usr/bin/html2pdf /usr/bin/html2png /bundle/plutobook/tools/

          libraries=$(lddtree -l /usr/lib64/libplutobook.so \
            | grep -v "libplutobook.so$" \
            | grep -v -e 'libgcc_s.so.1' \
                      -e 'libresolv.so.2' \
                      -e 'libpthread.so.0' \
                      -e 'libm.so.6' \
                      -e 'libdl.so.2' \
                      -e 'libexpat.so.1' \
                      -e 'libc.so.6' \
                      -e 'librt.so.1' \
                      -e 'libz.so.1' \
                      -e 'ld-linux-x86-64.so.2' \
                      -e 'libstdc++.so.6')

          for lib in $libraries; do
            soname=$(patchelf --print-soname "$lib")
            cp -v "$lib" "/bundle/plutobook/lib/$soname"
            patchelf --set-rpath '$ORIGIN' "/bundle/plutobook/lib/$soname"
            strip --strip-unneeded "/bundle/plutobook/lib/$soname"
          done

          patchelf --set-rpath '$ORIGIN' /bundle/plutobook/lib/libplutobook.so
          strip --strip-unneeded /bundle/plutobook/lib/libplutobook.so

          for tool in html2pdf html2png; do
            patchelf --set-rpath '$ORIGIN/../lib' /bundle/plutobook/tools/$tool
            strip --strip-unneeded /bundle/plutobook/tools/$tool
          done

          tar -czvf plutobook-linux-x64.tar.gz -C /bundle plutobook

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: plutobook-linux-x64
          path: plutobook-linux-x64.tar.gz
